# =================================================================================================
# This code is part of PyLith, developed through the Computational Infrastructure
# for Geodynamics (https://github.com/geodynamics/pylith).
#
# Copyright (c) 2010-2025, University of California, Davis and the PyLith Development Team.
# All rights reserved.
#
# See https://mit-license.org/ and LICENSE.md and for license information. 
# =================================================================================================

dist_noinst_PYTHON = \
    PVE_shells_2d_gmsh.py \

dist_noinst_DATA = \
    pve_mesh_tri.msh \
    pve_shells_2d.timedb
    pylithapp.cfg \
    step01_inflation.cfg \